### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Laser-Cho** [paulgavrikov/parallel-matplotlib-grid#5]
**Describe the bug**
TypeError: parallel_plot() got an unexpected keyword argument 'figsize'

I saw your blog post(https://towardsdatascience.com/plotting-in-parallel-with-matplotlib-and-python-f7efb3d944de) 
and try  scatter example has figsize option.

parallel_plot(plot_fn=scatter, data=X, grid_shape=(1, 5), figsize=(25, 5))

but it doesn't work. 

**Minimal Code To Reproduce**
parallel_plot(plot_fn=scatter, data=X, grid_shape=(1, 5), figsize=(25, 5))

**Expected behavior**
figsize option accepted

**Environment (please complete the following information):**
 - OS: WSL 
 - Python  Python 3.8
 - latest

**Additional context**

**Comment by paulgavrikov** [comment]
Hi, the code in the blog post was different - it was just to show how things work.
This library does not support the `figsize` argument. Instead, you can pass `grid_cell_size``which defines the size of each cell, and the library will compute the full figure size for you.

**Comment by Laser-Cho** [comment]
My fault. Sorry.

**Comment by paulgavrikov** [comment]
No worries! I am happy to help.

closing this now
